site_name: Franquia Social
# theme:
#     name: material
#     language: pt
#     features:
#         - navigation.tabs

nav:
    - Home: index.md
    - Arquitetura: 
        - Arquitetura: Arquitetura/arquitetura.md
    - Backlog: Backlog/backlog.md
    - Custo e Risco: 
        - Custo: Custo_Risco/custo.md
        - Risco: Custo_Risco/risco.md
    - EVM: 
        - EVM: EVM/evm.md
    - Guia de Contribuição: 
        - Guia de Contribuição: Guia_Contribuicao/guia_contribuicao.md  
    - Organização:
       - Metodologia: Organizacao/metodologia.md
       - Plano de Comunicação: Organizacao/plano_comunicacao.md
       - Quadros de Conhecimentos: Organizacao/quadro_conhecimento.md
    - Sprints e Releases:
        - Sprint 0: Sprints_Releases/sprint0.md
    - Visão de Produto:
        - Lean Inception: Visao_Produto/lean_inception.md
        - Visão de Produto: Visao_Produto/visao_pd.md
        - O produto É - NÃO É - FAZ - NÃO FAZ: Visao_Produto/produto_e_naoe.md
        - Objetivos do Produto: Visao_Produto/objetivos_produto.md
        - Personas: Visao_Produto/personas.md
        - Jornadas de Usuários: Visao_Produto/jornada_usuario.md
        - Brainstorming de Funcionalidades: Visao_Produto/brainstorming_func.md
        - Revisão Técnica, de Negócio e de UX: Visao_Produto/revisao_tecnica.md
        - Sequenciador: Visao_Produto/sequenciador.md
    - Visual:
        - Protótipo de Alta Fidelidade: Visual/prototipo_alta.md
        - Protótipo de Baixa Fidelidade: Visual/prototipo_baixa.md
